env: "local"
storage_path: "user=postgres password=1279660 dbname=MusicAppDB sslmode=disable"
redis:
  address: "localhost:6379"
  password: ""
  db: 0
http_server:
  address: "localhost:8085"
  timeout: 4s
  